# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/aflpp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protoc/aflpp.proto\x12\x05\x61\x63rux\"E\n\x0cStartRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06\x62inary\x18\x02 \x01(\x0c\x12\x13\n\x0b\x62inary_args\x18\x03 \x01(\t\"\x1d\n\nStartReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\r\n\x0bStopRequest\"\x1c\n\tStopReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32j\n\x05\x41\x46LPP\x12\x31\n\x05start\x12\x13.acrux.StartRequest\x1a\x11.acrux.StartReply\"\x00\x12.\n\x04stop\x12\x12.acrux.StopRequest\x1a\x10.acrux.StopReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoc.aflpp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STARTREQUEST']._serialized_start=29
  _globals['_STARTREQUEST']._serialized_end=98
  _globals['_STARTREPLY']._serialized_start=100
  _globals['_STARTREPLY']._serialized_end=129
  _globals['_STOPREQUEST']._serialized_start=131
  _globals['_STOPREQUEST']._serialized_end=144
  _globals['_STOPREPLY']._serialized_start=146
  _globals['_STOPREPLY']._serialized_end=174
  _globals['_AFLPP']._serialized_start=176
  _globals['_AFLPP']._serialized_end=282
# @@protoc_insertion_point(module_scope)
