# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aflpp_server.protoc.v1 import aflpp_pb2 as protoc_dot_v1_dot_aflpp__pb2


class AFLPPStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start = channel.unary_unary(
                '/aflpp.v1.AFLPP/start',
                request_serializer=protoc_dot_v1_dot_aflpp__pb2.StartRequest.SerializeToString,
                response_deserializer=protoc_dot_v1_dot_aflpp__pb2.StartResponse.FromString,
                )
        self.stop = channel.unary_unary(
                '/aflpp.v1.AFLPP/stop',
                request_serializer=protoc_dot_v1_dot_aflpp__pb2.StopRequest.SerializeToString,
                response_deserializer=protoc_dot_v1_dot_aflpp__pb2.StopResponse.FromString,
                )
        self.stats = channel.unary_unary(
                '/aflpp.v1.AFLPP/stats',
                request_serializer=protoc_dot_v1_dot_aflpp__pb2.StatisticRequest.SerializeToString,
                response_deserializer=protoc_dot_v1_dot_aflpp__pb2.StatisticResponse.FromString,
                )
        self.reports = channel.unary_stream(
                '/aflpp.v1.AFLPP/reports',
                request_serializer=protoc_dot_v1_dot_aflpp__pb2.ReportRequest.SerializeToString,
                response_deserializer=protoc_dot_v1_dot_aflpp__pb2.ReportResponse.FromString,
                )


class AFLPPServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AFLPPServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start': grpc.unary_unary_rpc_method_handler(
                    servicer.start,
                    request_deserializer=protoc_dot_v1_dot_aflpp__pb2.StartRequest.FromString,
                    response_serializer=protoc_dot_v1_dot_aflpp__pb2.StartResponse.SerializeToString,
            ),
            'stop': grpc.unary_unary_rpc_method_handler(
                    servicer.stop,
                    request_deserializer=protoc_dot_v1_dot_aflpp__pb2.StopRequest.FromString,
                    response_serializer=protoc_dot_v1_dot_aflpp__pb2.StopResponse.SerializeToString,
            ),
            'stats': grpc.unary_unary_rpc_method_handler(
                    servicer.stats,
                    request_deserializer=protoc_dot_v1_dot_aflpp__pb2.StatisticRequest.FromString,
                    response_serializer=protoc_dot_v1_dot_aflpp__pb2.StatisticResponse.SerializeToString,
            ),
            'reports': grpc.unary_stream_rpc_method_handler(
                    servicer.reports,
                    request_deserializer=protoc_dot_v1_dot_aflpp__pb2.ReportRequest.FromString,
                    response_serializer=protoc_dot_v1_dot_aflpp__pb2.ReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aflpp.v1.AFLPP', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AFLPP(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aflpp.v1.AFLPP/start',
            protoc_dot_v1_dot_aflpp__pb2.StartRequest.SerializeToString,
            protoc_dot_v1_dot_aflpp__pb2.StartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aflpp.v1.AFLPP/stop',
            protoc_dot_v1_dot_aflpp__pb2.StopRequest.SerializeToString,
            protoc_dot_v1_dot_aflpp__pb2.StopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aflpp.v1.AFLPP/stats',
            protoc_dot_v1_dot_aflpp__pb2.StatisticRequest.SerializeToString,
            protoc_dot_v1_dot_aflpp__pb2.StatisticResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/aflpp.v1.AFLPP/reports',
            protoc_dot_v1_dot_aflpp__pb2.ReportRequest.SerializeToString,
            protoc_dot_v1_dot_aflpp__pb2.ReportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
